name: Docker Compose Action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose.yaml"

      - name: 'Wait until the database is healthy'
        uses: raschmitt/wait-for-healthy-container/@master
        with:
          container-name: database
          timeout: 30

      - name: 'Wait until the frontend is healthy'
        uses: raschmitt/wait-for-healthy-container/@master
        with:
          container-name: frontend
          timeout: 60

      - name: 'Wait until the backend is healthy'
        uses: raschmitt/wait-for-healthy-container/@master
        with:
          container-name: backend
          timeout: 60

      - name: 'API tests'
        run: |
            SpaceResponse=$(curl --fail --show-error --request POST \
              --url "http://localhost:8080/api/spaces" \
              --header 'Content-Type: application/json' \
              --data '{"name": "Sample Space"}')
            SpaceId=$(echo "$SpaceResponse" | jq -r '.id')
            Space=$(curl --fail --show-error --request GET \
            --url "http://localhost:8080/api/spaces/$SpaceId" \
            --header 'Content-Type: application/json')

            SemesterResponse=$(curl --fail --show-error --request POST \
              --url "http://localhost:8080/api/spaces/$SpaceId/semesters" \
              --header 'Content-Type: application/json' \
              --data '{"name": "Sample Semester"}')
            SemesterId=$(echo "$SemesterResponse" | jq -r '.id')
            Semester=$(curl --fail --show-error --request GET \
            --url "http://localhost:8080/api/spaces/$SpaceId/semesters/$SemesterId" \
            --header 'Content-Type: application/json')

            SubjectResponse=$(curl --fail --show-error --request POST \
              --url "http://localhost:8080/api/spaces/$SpaceId/semesters/$SemesterId/subjects" \
              --header 'Content-Type: application/json' \
              --data '{"name": "Sample Subject"}')
            SubjectId=$(echo "$SubjectResponse" | jq -r '.id')
            Subject=$(curl --fail --show-error --request GET \
            --url "http://localhost:8080/api/spaces/$SpaceId/semesters/$SemesterId/subjects/$SubjectId" \
            --header 'Content-Type: application/json')

            GradeResponse=$(curl --fail --show-error --request POST \
              --url "http://localhost:8080/api/spaces/$SpaceId/semesters/$SemesterId/subjects/$SubjectId/grades" \
              --header 'Content-Type: application/json' \
              --data '{"name": "Sample Grade", "grade": 5.0, "gradeWeight": 1.0, "examDate": "2023-10-01T00:00:00Z"}')
            GradeId=$(echo "$GradeResponse" | jq -r '.id')
            Grade=$(curl --fail --show-error --request GET \
            --url "http://localhost:8080/api/spaces/$SpaceId/semesters/$SemesterId/subjects/$SubjectId/grades/$GradeId" \
            --header 'Content-Type: application/json')
